"""Render declaration drafts as DOCX (working and clean modes)."""

from __future__ import annotations

import io
import re
import uuid
from dataclasses import dataclass
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any, Final, Literal

import structlog
from docx import Document
from docx.enum.text import WD_LINE_SPACING, WD_TAB_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt
from docx.text.paragraph import Paragraph

from declarations.flags import unresolved_required_flag_ids
from declarations.schemas import (
    DeclarationDraftContent,
    DeclarationFlag,
    DeclarationFlagType,
    DeclarationParagraph,
    TranscriptSegment,
)
from wf_docx.ooxml_annotations import (
    CommentSpec,
    CommentStore,
    FootnoteSpec,
    FootnoteStore,
    ShadingSpec,
    inject_comments_and_footnotes,
    rebuild_paragraph_with_annotations,
)
from wf_docx.section_labels import (
    ELEMENT_KEY_SECTION,
    ordered_section_ids,
    section_heading,
)

log = structlog.get_logger()

_TEMPLATE_PATH: Final[Path] = (
    Path(__file__).resolve().parent / "templates" / "declaration.docx"
)

_PLACEHOLDER_CAPTION: Final[str] = "{{CAPTION}}"
_PLACEHOLDER_TITLE: Final[str] = "{{DECLARATION_TITLE}}"
_PLACEHOLDER_DATE: Final[str] = "{{DRAFT_DATE}}"
_PLACEHOLDER_SIGNATURE: Final[str] = "{{SIGNATURE_BLOCK}}"

_FOOTER_DISCLAIMER: Final[str] = (
    "Generated by Wellfounded. Attorney review required. Not legal advice."
)

_DEFAULT_TITLE: Final[str] = "DECLARATION IN SUPPORT OF ASYLUM APPLICATION"
_DEFAULT_SIGNATURE: Final[str] = (
    "I declare under penalty of perjury that the foregoing is true and correct.\n\n"
    "Executed on: _______________\n\n"
    "Signature: _______________"
)


class CleanExportBlockedError(Exception):
    """Raised when clean export is requested with open required flags."""

    def __init__(self, unresolved_flag_ids: list[uuid.UUID]) -> None:
        self.unresolved_flag_ids = unresolved_flag_ids
        n = len(unresolved_flag_ids)
        super().__init__(f"Clean export blocked: {n} unresolved required flag(s)")


@dataclass(frozen=True)
class DeclarationRenderInput:
    draft: DeclarationDraftContent
    flags: list[DeclarationFlag]
    case_pseudonym: str
    country_code: str
    draft_version: int
    generated_at: datetime | None
    transcript_segments: list[TranscriptSegment] | None = None
    parallel: bool = False


@dataclass
class _ParagraphAnchor:
    paragraph_id: str
    paragraph: Paragraph
    text: str


def render_clean_copy(inp: DeclarationRenderInput) -> bytes:
    """Plain declaration DOCX; raises if required flags remain open."""
    blocked = unresolved_required_flag_ids(inp.flags)
    if blocked:
        raise CleanExportBlockedError(blocked)
    return _build_docx_bytes(inp, working=False)


def render_working_copy(inp: DeclarationRenderInput) -> bytes:
    """Declaration DOCX with comments, inference shading, and ambiguity footnotes."""
    return _build_docx_bytes(inp, working=True)


def export_declaration_docx_filename(
    case_pseudonym: str,
    draft_version: int,
    mode: Literal["working", "clean"],
    *,
    parallel: bool = False,
) -> str:
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", case_pseudonym).strip("._-")[:80]
    if not safe:
        safe = "case"
    suffix = f"{mode}_parallel" if parallel else mode
    return f"declaration_v{draft_version}_{safe}_{suffix}.docx"


def _build_docx_bytes(inp: DeclarationRenderInput, *, working: bool) -> bytes:
    if not _TEMPLATE_PATH.is_file():
        raise FileNotFoundError(
            f"DOCX template missing at {_TEMPLATE_PATH}; add declaration.docx",
        )
    if inp.parallel and inp.transcript_segments is None:
        raise ValueError("transcript_segments required when parallel=True")

    document = Document(str(_TEMPLATE_PATH))
    _apply_document_defaults(document)
    draft_date = _draft_date_iso(inp.generated_at)
    caption = f"{inp.case_pseudonym} — {inp.country_code.upper()}"
    _replace_placeholders(
        document,
        {
            _PLACEHOLDER_CAPTION: caption,
            _PLACEHOLDER_TITLE: _DEFAULT_TITLE,
            _PLACEHOLDER_DATE: draft_date,
            _PLACEHOLDER_SIGNATURE: _DEFAULT_SIGNATURE,
        },
    )

    comment_store = CommentStore()
    footnote_store = FootnoteStore()
    anchors: list[_ParagraphAnchor] = []
    segment_source = _segment_source_map(inp.transcript_segments)

    for section_id in ordered_section_ids():
        section = inp.draft.sections[section_id]
        document.add_heading(section_heading(section_id), level=2)
        anchors.append(
            _ParagraphAnchor(
                paragraph_id=f"{section_id}:heading",
                paragraph=document.paragraphs[-1],
                text=section_heading(section_id),
            ),
        )

        if inp.parallel:
            table = document.add_table(rows=1, cols=2)
            table.style = "Table Grid"
            hdr = table.rows[0].cells
            hdr[0].text = "Source language"
            hdr[1].text = "English"
            para_num = 0
            for para in section.paragraphs:
                para_num += 1
                row = table.add_row().cells
                row[0].text = _source_text_for_paragraph(para, segment_source)
                p_en = row[1].paragraphs[0]
                _clear_paragraph(p_en)
                anchors.append(
                    _fill_body_paragraph(
                        p_en,
                        para,
                        para_num=para_num,
                        working=working,
                        comment_store=comment_store,
                        footnote_store=footnote_store,
                        flags=inp.flags,
                    ),
                )
        else:
            para_num = 0
            for para in section.paragraphs:
                para_num += 1
                p = document.add_paragraph()
                anchors.append(
                    _fill_body_paragraph(
                        p,
                        para,
                        para_num=para_num,
                        working=working,
                        comment_store=comment_store,
                        footnote_store=footnote_store,
                        flags=inp.flags,
                    ),
                )

    if working:
        _attach_gap_comments(inp, anchors, comment_store)

    _apply_footers(document)

    buf = io.BytesIO()
    document.save(buf)
    raw = buf.getvalue()
    if working and (comment_store.specs or footnote_store.bodies):
        raw = inject_comments_and_footnotes(
            raw,
            comment_store=comment_store,
            footnote_store=footnote_store,
        )
    return raw


def _fill_body_paragraph(
    paragraph: Paragraph,
    para: DeclarationParagraph,
    *,
    para_num: int,
    working: bool,
    comment_store: CommentStore,
    footnote_store: FootnoteStore,
    flags: list[DeclarationFlag],
) -> _ParagraphAnchor:
    display_text = f"{para_num}. {para.text}"
    anchor = _ParagraphAnchor(
        paragraph_id=para.id,
        paragraph=paragraph,
        text=display_text,
    )
    if not working:
        paragraph.add_run(display_text)
        return anchor

    prefix_len = len(f"{para_num}. ")
    para_flags = [f for f in flags if f.paragraph_id == para.id]
    comments: list[CommentSpec] = []
    shadings: list[ShadingSpec] = []
    footnotes: list[FootnoteSpec] = []

    for fl in para_flags:
        s = prefix_len + fl.span.start
        e = prefix_len + fl.span.end
        body = _flag_comment_body(fl)
        if fl.type == DeclarationFlagType.AMBIGUITY:
            fid = footnote_store.add(start=s, end=e, text=body)
            footnotes.append(FootnoteSpec(footnote_id=fid, start=s, end=e, text=body))
        else:
            cid = comment_store.add(start=s, end=e, text=body)
            comments.append(
                CommentSpec(
                    comment_id=cid,
                    start=s,
                    end=e,
                    author="Wellfounded",
                    text=body,
                ),
            )

    for inf in para.inference_spans:
        shadings.append(
            ShadingSpec(start=prefix_len + inf.start, end=prefix_len + inf.end),
        )

    for fl in para_flags:
        if fl.type == DeclarationFlagType.INFERENCE:
            s0 = prefix_len + fl.span.start
            s1 = prefix_len + fl.span.end
            shadings.append(ShadingSpec(start=s0, end=s1))

    rebuild_paragraph_with_annotations(
        paragraph,
        display_text,
        comments=comments,
        shadings=shadings,
        footnotes=footnotes,
    )
    return anchor


def _attach_gap_comments(
    inp: DeclarationRenderInput,
    anchors: list[_ParagraphAnchor],
    comment_store: CommentStore,
) -> None:
    by_para: dict[str, _ParagraphAnchor] = {a.paragraph_id: a for a in anchors}

    for fl in inp.flags:
        if fl.type != DeclarationFlagType.GAP or not fl.paragraph_id.startswith("gap:"):
            continue
        element_key = fl.paragraph_id.removeprefix("gap:")
        section_id = ELEMENT_KEY_SECTION.get(element_key, "identity_background")
        heading_id = f"{section_id}:heading"
        target = by_para.get(heading_id)
        if target is None:
            log.warning(
                "declaration_docx_gap_anchor_missing",
                element_key=element_key,
                section_id=section_id,
            )
            continue
        body = _flag_comment_body(fl)
        cid = comment_store.add(start=0, end=0, text=body)
        rebuild_paragraph_with_annotations(
            target.paragraph,
            target.text,
            comments=[
                CommentSpec(
                    comment_id=cid,
                    start=0,
                    end=0,
                    author="Wellfounded",
                    text=body,
                ),
            ],
            shadings=[],
            footnotes=[],
        )


def _flag_comment_body(flag: DeclarationFlag) -> str:
    parts = [
        f"[{flag.type.value}]",
        flag.description,
        f"Suggested resolution: {flag.suggested_resolution}",
    ]
    if flag.resolution_note:
        parts.append(f"Resolution note: {flag.resolution_note}")
    if flag.status.value != "open":
        parts.append(f"Status: {flag.status.value}")
    return "\n".join(parts)


def _source_text_for_paragraph(
    para: DeclarationParagraph,
    segment_source: dict[str, str],
) -> str:
    chunks: list[str] = []
    for seg_id in para.source_segment_ids:
        text = segment_source.get(seg_id)
        if text:
            chunks.append(text)
    return "\n\n".join(chunks) if chunks else ""


def _segment_source_map(
    segments: list[TranscriptSegment] | None,
) -> dict[str, str]:
    if segments is None:
        return {}
    return {f"seg-{i}": seg.source_text for i, seg in enumerate(segments)}


def _draft_date_iso(generated_at: datetime | None) -> str:
    if generated_at is not None:
        return generated_at.astimezone(UTC).date().isoformat()
    return date.today().isoformat()


def _clear_paragraph(paragraph: Paragraph) -> None:
    p_el = paragraph._p
    for child in list(p_el):
        if child.tag == qn("w:r"):
            p_el.remove(child)


def _replace_placeholders(document: Any, mapping: dict[str, str]) -> None:
    for p in document.paragraphs:
        for key, val in mapping.items():
            if key in p.text:
                p.text = p.text.replace(key, val)
    for table in document.tables:
        for row in table.rows:
            for cell in row.cells:
                for p in cell.paragraphs:
                    for key, val in mapping.items():
                        if key in p.text:
                            p.text = p.text.replace(key, val)


def _append_page_field(paragraph: Paragraph) -> None:
    fld = OxmlElement("w:fldSimple")
    fld.set(qn("w:instr"), "PAGE")
    paragraph._p.append(fld)


def _apply_document_defaults(document: Any) -> None:
    normal = document.styles["Normal"]
    normal.font.name = "Source Serif Pro"
    normal.font.size = Pt(11)
    normal.paragraph_format.line_spacing_rule = WD_LINE_SPACING.MULTIPLE
    normal.paragraph_format.line_spacing = 1.15
    for sec in document.sections:
        sec.top_margin = Inches(1)
        sec.bottom_margin = Inches(1)
        sec.left_margin = Inches(1)
        sec.right_margin = Inches(1)


def _apply_footers(document: Any) -> None:
    for sec in document.sections:
        footer = sec.footer
        for child in list(footer._element):
            footer._element.remove(child)
        p = footer.add_paragraph()
        p.paragraph_format.tab_stops.add_tab_stop(
            Inches(6.5),
            WD_TAB_ALIGNMENT.RIGHT,
        )
        p.add_run(_FOOTER_DISCLAIMER + "\t")
        _append_page_field(p)
