"""Render a country conditions memo as DOCX (template + python-docx)."""

from __future__ import annotations

import io
import re
import uuid
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Any, Final

from docx import Document
from docx.enum.text import WD_BREAK, WD_LINE_SPACING, WD_TAB_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt
from docx.text.paragraph import Paragraph

from country_conditions.docx_hyperlink import add_external_hyperlink
from country_conditions.schemas import (
    CC_SECTION_IDS,
    CountryConditionsInputs,
    FinalMemoStructured,
    MemoSectionStructured,
    passage_ids_in_prose,
)
from retrieval.models import SourceFamily
from retrieval.schemas import PassageExportMeta

# Template lives beside this module; edited in Word (fonts, margins). Do not rename
# `python-docx` import package to `docx` — this module lives under `country_conditions/`
# so it does not shadow the third-party `docx` library.
_TEMPLATE_PATH: Final[Path] = (
    Path(__file__).resolve().parent / "templates" / "country_conditions.docx"
)

_PLACEHOLDER_CAPTION: Final[str] = "{{CAPTION}}"
_PLACEHOLDER_MEMO_TITLE: Final[str] = "{{MEMO_TITLE}}"
_PLACEHOLDER_MEMO_DATE: Final[str] = "{{MEMO_DATE}}"

_FOOTER_DISCLAIMER: Final[str] = (
    "Generated by Wellfounded. Attorney review required. Not legal advice."
)

_CITE_TAG_RE = re.compile(
    r'<cite\s+passage_id="([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-'
    r'[0-9a-fA-F]{4}-[0-9a-fA-F]{12})"\s*/>',
)


def _source_family_label(family_key: str) -> str:
    try:
        fam = SourceFamily(family_key)
    except ValueError:
        return family_key.replace("_", " ").title()
    labels: dict[SourceFamily, str] = {
        SourceFamily.state_dept_human_rights: "U.S. Department of State",
        SourceFamily.uscirf: "U.S. Commission on International Religious Freedom",
        SourceFamily.unhcr: "UNHCR",
        SourceFamily.hrc_upr: "UN Human Rights Council (UPR)",
        SourceFamily.hrw: "Human Rights Watch",
        SourceFamily.amnesty: "Amnesty International",
        SourceFamily.freedom_house: "Freedom House",
        SourceFamily.cpj: "Committee to Protect Journalists",
        SourceFamily.euaa_coi: "European Union Agency for Asylum",
        SourceFamily.academic: "Academic / other",
    }
    return labels.get(fam, family_key.replace("_", " ").title())


def _ordered_cited_passage_ids(
    sections: list[MemoSectionStructured],
) -> list[uuid.UUID]:
    ordered: list[uuid.UUID] = []
    seen: set[uuid.UUID] = set()
    for sec in sections:
        for pid in passage_ids_in_prose(sec.body):
            if pid not in seen:
                seen.add(pid)
                ordered.append(pid)
    return ordered


def _sorted_bibliography_rows(
    ordered_unique_passage_ids: list[uuid.UUID],
    meta: dict[uuid.UUID, PassageExportMeta],
) -> list[PassageExportMeta]:
    rows = [meta[pid] for pid in ordered_unique_passage_ids]
    return sorted(
        rows,
        key=lambda m: (
            m.source_family.lower(),
            -m.publication_date.toordinal(),
            m.document_title.lower(),
            str(m.passage_id),
        ),
    )


def _citation_index_by_passage_id(
    sorted_rows: list[PassageExportMeta],
) -> dict[uuid.UUID, int]:
    return {m.passage_id: i for i, m in enumerate(sorted_rows, start=1)}


def _replace_placeholders(document: Any, mapping: dict[str, str]) -> None:
    for p in document.paragraphs:
        for key, val in mapping.items():
            if key in p.text:
                p.text = p.text.replace(key, val)
    for table in document.tables:
        for row in table.rows:
            for cell in row.cells:
                for p in cell.paragraphs:
                    for key, val in mapping.items():
                        if key in p.text:
                            p.text = p.text.replace(key, val)


def _append_page_field(paragraph: Paragraph) -> None:
    fld = OxmlElement("w:fldSimple")
    fld.set(qn("w:instr"), "PAGE")
    paragraph._p.append(fld)


def _apply_document_defaults(document: Any) -> None:
    normal = document.styles["Normal"]
    normal.font.name = "Source Serif Pro"
    normal.font.size = Pt(11)
    normal.paragraph_format.line_spacing_rule = WD_LINE_SPACING.MULTIPLE
    normal.paragraph_format.line_spacing = 1.15
    for sec in document.sections:
        sec.top_margin = Inches(1)
        sec.bottom_margin = Inches(1)
        sec.left_margin = Inches(1)
        sec.right_margin = Inches(1)


def _apply_footers(document: Any) -> None:
    for sec in document.sections:
        footer = sec.footer
        for child in list(footer._element):
            footer._element.remove(child)
        p = footer.add_paragraph()
        p.paragraph_format.tab_stops.add_tab_stop(
            Inches(6.5),
            WD_TAB_ALIGNMENT.RIGHT,
        )
        p.add_run(_FOOTER_DISCLAIMER + "\t")
        _append_page_field(p)


def _safe_http_url(url: str) -> str | None:
    u = url.strip()
    if len(u) > 8_192:
        return None
    if u.startswith("https://") or u.startswith("http://"):
        return u
    return None


def _append_prose_with_citations(
    paragraph: Paragraph,
    text: str,
    *,
    index_by_pid: dict[uuid.UUID, int],
    url_by_pid: dict[uuid.UUID, str],
) -> None:
    pos = 0
    for m in _CITE_TAG_RE.finditer(text):
        if m.start() > pos:
            paragraph.add_run(text[pos : m.start()])
        pid = uuid.UUID(m.group(1))
        n = index_by_pid[pid]
        raw_url = url_by_pid[pid]
        href = _safe_http_url(raw_url)
        if href is not None:
            add_external_hyperlink(
                paragraph,
                str(n),
                href,
                superscript=True,
            )
        else:
            r = paragraph.add_run(str(n))
            r.font.superscript = True
        pos = m.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])


def _add_body_blocks(
    document: Any,
    body: str,
    *,
    index_by_pid: dict[uuid.UUID, int],
    url_by_pid: dict[uuid.UUID, str],
) -> None:
    blocks = body.split("\n\n")
    for block in blocks:
        if not block.strip():
            continue
        p = document.add_paragraph()
        lines = block.split("\n")
        for i, line in enumerate(lines):
            if i > 0:
                p.add_run().add_break(WD_BREAK.LINE)
            _append_prose_with_citations(
                p,
                line,
                index_by_pid=index_by_pid,
                url_by_pid=url_by_pid,
            )


def _sections_ordered(final: FinalMemoStructured) -> list[MemoSectionStructured]:
    by_id = {s.section_id: s for s in final.sections}
    out: list[MemoSectionStructured] = []
    for sid in CC_SECTION_IDS:
        sec = by_id.get(sid)
        if sec is None:
            raise ValueError(f"final memo missing section_id {sid!r}")
        out.append(sec)
    return out


def cited_passage_ids_ordered(final: FinalMemoStructured) -> list[uuid.UUID]:
    """Unique passage IDs in first-appearance order (matches superscript assignment)."""
    return _ordered_cited_passage_ids(_sections_ordered(final))


def build_country_conditions_docx_bytes(
    *,
    final: FinalMemoStructured,
    inputs: CountryConditionsInputs,
    case_pseudonym: str,
    export_meta: dict[uuid.UUID, PassageExportMeta],
    memo_generated_at: datetime | None,
) -> bytes:
    """Build DOCX bytes from structured memo output and retrieval-backed metadata."""
    if not _TEMPLATE_PATH.is_file():
        raise FileNotFoundError(
            f"DOCX template missing at {_TEMPLATE_PATH}; add country_conditions.docx",
        )

    ordered_ids = _ordered_cited_passage_ids(_sections_ordered(final))
    sorted_rows = _sorted_bibliography_rows(ordered_ids, export_meta)
    index_by_pid = _citation_index_by_passage_id(sorted_rows)
    url_by_pid = {pid: export_meta[pid].url for pid in index_by_pid}

    if memo_generated_at is not None:
        memo_date = memo_generated_at.astimezone(UTC).date().isoformat()
    else:
        memo_date = date.today().isoformat()

    caption = f"{case_pseudonym} — {inputs.country_code}"
    memo_title = "Country conditions memorandum"

    document = Document(str(_TEMPLATE_PATH))
    _apply_document_defaults(document)
    _replace_placeholders(
        document,
        {
            _PLACEHOLDER_CAPTION: caption,
            _PLACEHOLDER_MEMO_TITLE: memo_title,
            _PLACEHOLDER_MEMO_DATE: memo_date,
        },
    )

    for sec in _sections_ordered(final):
        document.add_heading(sec.title, level=2)
        _add_body_blocks(
            document,
            sec.body,
            index_by_pid=index_by_pid,
            url_by_pid=url_by_pid,
        )

    document.add_heading("Bibliography", level=2)
    for i, row in enumerate(sorted_rows, start=1):
        org = _source_family_label(row.source_family)
        pub = row.publication_date.isoformat()
        verified = row.last_verified_at.astimezone(UTC).date().isoformat()
        p = document.add_paragraph()
        head = (
            f"{i}. {org}. {row.document_title}. "
            f"Published {pub}. URL: "
        )
        p.add_run(head)
        href = _safe_http_url(row.url)
        if href is not None:
            add_external_hyperlink(p, row.url, href)
        else:
            p.add_run(row.url)
        p.add_run(f" Last verified: {verified}.")

    _apply_footers(document)

    buf = io.BytesIO()
    document.save(buf)
    return buf.getvalue()


def export_docx_filename(case_pseudonym: str, memo_version: int) -> str:
    """ASCII-safe attachment filename for Content-Disposition."""
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", case_pseudonym).strip("._-")[:80]
    if not safe:
        safe = "case"
    return f"country_conditions_v{memo_version}_{safe}.docx"
